# Generated by Django 6.0.4 on 2026-04-29 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('start_ts', models.BigIntegerField()),
                ('end_ts', models.BigIntegerField()),
                ('parameters', models.JSONField(default=dict)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('regime', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NEUTRAL', 'Neutral'), ('BULLISH_IMPULSE', 'Bullish Impulse'), ('BEARISH_IMPULSE', 'Bearish Impulse'), ('BULLISH_EXTREME', 'Bullish Extreme'), ('BEARISH_EXTREME', 'Bearish Extreme'), ('REGIME_SHIFT', 'Regime Shift'), ('TRENDING', 'Trending'), ('CYCLING', 'Cycling'), ('NOISY', 'Noisy')], max_length=20)),
                ('previous_regime', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NEUTRAL', 'Neutral'), ('BULLISH_IMPULSE', 'Bullish Impulse'), ('BEARISH_IMPULSE', 'Bearish Impulse'), ('BULLISH_EXTREME', 'Bullish Extreme'), ('BEARISH_EXTREME', 'Bearish Extreme'), ('REGIME_SHIFT', 'Regime Shift'), ('TRENDING', 'Trending'), ('CYCLING', 'Cycling'), ('NOISY', 'Noisy')], default='UNKNOWN', max_length=20)),
                ('confidence', models.FloatField()),
                ('started_at', models.BigIntegerField()),
                ('ended_at', models.BigIntegerField(blank=True, null=True)),
                ('duration_candles', models.IntegerField(default=0)),
                ('avg_zscore', models.FloatField(default=0.0)),
                ('avg_noise', models.FloatField(default=0.0)),
                ('fft_period', models.FloatField(default=64.0)),
                ('transition_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('interval_sec', models.IntegerField()),
                ('source', models.CharField(choices=[('synthetic', 'Synthetic'), ('alpaca', 'Alpaca'), ('yahoo', 'Yahoo Finance'), ('manual', 'Manual')], default='synthetic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_cand_symbol_4ed5e4_idx')],
                'unique_together': {('symbol', 'timestamp', 'interval_sec')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('model_version', models.CharField(default='v1', max_length=20)),
                ('predicted', models.FloatField()),
                ('actual', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('horizon', models.IntegerField()),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='market.experimentrun')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('event_type', models.CharField(choices=[('BULLISH_EXTREME', 'Bullish Extreme'), ('BEARISH_EXTREME', 'Bearish Extreme'), ('REGIME_SHIFT', 'Regime Shift'), ('BULLISH_IMPULSE', 'Bullish Impulse'), ('BEARISH_IMPULSE', 'Bearish Impulse')], max_length=20)),
                ('price', models.FloatField()),
                ('zscore', models.FloatField()),
                ('noise', models.FloatField()),
                ('noise_zscore', models.FloatField()),
                ('confidence', models.FloatField()),
                ('timestamp', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='market.regimestate')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SignalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolling_mean', models.FloatField()),
                ('rolling_std', models.FloatField()),
                ('zscore', models.FloatField()),
                ('filtered', models.FloatField()),
                ('noise', models.FloatField()),
                ('noise_zscore', models.FloatField()),
                ('fft_period', models.FloatField()),
                ('fft_power', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='market.candle')),
                ('regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='market.regimestate')),
            ],
            options={
                'ordering': ['-candle__timestamp'],
            },
        ),
    ]
